name: Dodatek 1

on:
  push:
    branches: [master]

env:
  IMAGE_NAME: technologie_chmurowe_zadanie_1:latest

jobs:
  build-and-push:
    name: Build and push images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure Buildx
        uses: docker/setup-buildx-action@v1

      - name: Sign in to image registry - DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Sign in to image registry - GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm/v7, linux/arm64/v8, linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }},${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha
